In [2]:
import pandas as pd
import numpy as np
import pyfpgrowth as pf

In [9]:
transactions = pd.read_csv('scripts/fpm-final.tsv', sep='\t', names = ['tid', 'asin', 'type', 'similar'])

In [19]:
transactions = transactions.drop(transactions[transactions.type != 'Book'].index)
transactions

,tid,asin,type,similar
0,1,0827229534,Book,"0804215715,156101074X,0687023955,0687074231,08..."
1,2,0738700797,Book,"0738700827,1567184960,1567182836,0738700525,07..."
2,3,0486287785,Book,NaN
3,4,0842328327,Book,"0842328130,0830818138,0842330313,0842328610,08..."
4,5,1577943082,Book,"157794349X,0892749504,1577941829,0892749563,15..."
5,6,0486220125,Book,"0486401960,0452283612,0486229076,0714840343,03..."
7,8,0231118597,Book,"B000067D0Y,0375727191,080148605X,1560232579,03..."
8,9,1859677800,Book,NaN
9,10,0375709363,Book,"039474067X,0679730672,0679750541,1400030668,08..."
10,11,0871318237,Book,"1591200695,0060984341,0553577514,1571742972,09..."
11,12,1590770218,Book,"0871319640,0399530258,1590770536,158040197X,15..."
12,13,0313230269,Book,NaN
14,15,1559362022,Book,"1559360968,1559361247,1559360828,1559361018,07..."
15,16,0195110382,Book,"1585741485,0140246967,1557504288,0374205183,05..."
16,17,0849311012,Book,"0071410546,1580531784,1578200326,B0000A2W55"
18,19,078510870X,Book,"0785114572,078511078X,0785114033,0785114041,07..."
19,20,3895780812,Book,"0865778973,0071343547,0721662854,0721681735,08..."
22,23,0393049388,Book,NaN
23,24,0553525476,Book,NaN
24,25,0939165252,Book,"059500055X,B00026L9CU,0471426121,0791453200,06..."
25,26,1590930509,Book,"0439078172,0899192254,0688070450,0899193498,15..."
26,27,0231096704,Book,"0385492286,0300080883,0140172483,0375707409,05..."
27,28,1893732290,Book,"189373238X,1893732398,0609805797"
28,29,0781718791,Book,"0071360387,0323016774,0781735114,0721601855,07..."
29,30,0471150274,Book,"0471203092,013061081X,0130081779,1852331666,00..."
30,31,0895872218,Book,"1892514656,0399151834,0767908090"
31,32,0761116982,Book,"1579652395,0393020436,0767903609,0312290233,04..."
32,33,0439240751,Book,"0439492327,0439240727,0439240719,0439240700,00..."
34,35,0618111212,Book,"0395816556,0395960592,061822694X,0395698235,06..."
35,36,1898630038,Book,NaN
...,...,...,...,...
542646,548514,0963542613,Book,"0963542648,0963542605,1556523157,0471387533,19..."
542647,548515,0785111263,Book,"0785111271,0785112472,0785115285,0785110461,07..."
542648,548516,8475090362,Book,NaN
542649,548517,0964838222,Book,NaN
542650,548518,9684320477,Book,"0802133908,0140266216,9872056218,843760494X,15..."
542651,548519,088363337X,Book,"0805058443,0195051874,0811827836,038549596X"
542652,548520,0465028721,Book,"0684835657,0198205287,0521627249,0521596491,05..."
542653,548521,2060000912,Book,"1886705410,0789494302,2060000335,1886590079,20..."
542654,548522,4770027613,Book,"0804832625,158685027X,4770023537,0811836754,08..."
542655,548523,1552780597,Book,NaN
542656,548524,0575068957,Book,"0575073330,0345440676,0060575301,0441010083,04..."
542657,548525,1567997554,Book,NaN
542659,548527,0743001370,Book,NaN
542660,548528,0945199198,Book,NaN
542661,548529,0310208084,Book,"0310479711,0802436471,0684856093,155874777X,07..."
542662,548530,0006176909,Book,"0006471641,0006477097,B00009MGGI,0006497993,06..."
542663,548531,0786632550,Book,"079357000X,0793529395,0793585031,0634002066"
542664,548532,0752808990,Book,NaN
542665,548533,4770023286,Book,"4770029446,1570624895"
542666,548534,0838409342,Book,"0838426069,080131531X,0838426247,0884897257,08..."
542667,548535,0552139432,Book,NaN
542669,548537,B00006RGI2,Book,"1930722214,0517163101,1930722052,0887306314,03..."
542670,548538,B000067JZT,Book,"B0006H0HFU,B0006Q1UMA,B0002GTW7Y,B0002Z0M6A,B0..."
542671,548539,B00008MNUJ,Book,"0822959046,140006256X,0195093852,0760734062,06..."
542672,548540,0060537612,Book,"0689808747,0689820305,0859531821,0060266864,09..."
542673,548541,9700507734,Book,NaN
542674,548542,9627762644,Book,NaN
542675,548543,0970020503,Book,NaN
542678,548546,1930519206,Book,NaN
542681,548549,0879736836,Book,"1931709920,188187110X,081890643X,1580510469,08..."

In [21]:
asin_main = transactions.asin
similar = transactions.similar